# Generated by Django 4.2.16 on 2024-11-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.IntegerField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=255)),
                ("book_launch_date", models.DateField()),
                ("book_publisher", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cat_id", models.IntegerField(primary_key=True, serialize=False)),
                ("cat_name", models.CharField(max_length=100)),
                (
                    "sub_cat_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "collection_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("collection_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("mem_id", models.IntegerField(primary_key=True, serialize=False)),
                ("mem_name", models.CharField(max_length=100)),
                ("mem_phone", models.CharField(max_length=15)),
                ("mem_email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "membership_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=40)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issuance",
            fields=[
                ("issuance_id", models.IntegerField(primary_key=True, serialize=False)),
                ("issuance_date", models.DateTimeField()),
                ("issued_by", models.CharField(max_length=100)),
                ("target_return_date", models.DateTimeField()),
                ("issuance_status", models.CharField(max_length=40)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.book",
                    ),
                ),
                (
                    "issuance_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="book_cat_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="library_app.category"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="book_collection_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="library_app.collection"
            ),
        ),
    ]
